### ISSUE TITLE
소스백업

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#152]
https://github.com/yjhwang93/gamess.www/tree/master/gamess.co.kr_www
에 백업하도록 설정

매주 월요일 2시에 commit하도록 함.

**Comment by seungchan100** [comment]
admin 폴더도 백업되게 해야함.
보안 risk 없애도록해야함.

**Comment by seungchan100** [comment]
admin 폴더도 백업되게 처리함

**Comment by seungchan100** [comment]
admin 폴더 백업안되게 처리함
