### ISSUE TITLE
[버그/관리자] 상세 자료에 대한 자료 수정이 안됨

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#167]
https://admin.gamess.kr/board_list_admin_detail.php?num=20663&table=pds_game

문제점 : 자료 수정 후 저장 시 하얀 화면이 나오면서 아무런 반응이 없음,

**Comment by seungchan100** [comment]
얽혀있는게 많아, 수정필요한 부분이 많습니다. 
기존 경로로 재이동해야할거 같습니다.

**Comment by seungchan100** [comment]
기존 yjhwang으로 이동

**Comment by yjhwang93** [comment]
ㅇㅋ

**Comment by yjhwang93** [comment]
yjhwang 이관이후에도 수정이 안됨

https://www.gamess.co.kr/yjhwang/board_list_admin_detail.php?num=20695&table=pds_game

**Comment by seungchan100** [comment]
조치하였습니다.
