### ISSUE TITLE
게임명 입력안되어있으면 자료등록 불가하도록

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#171]

**Comment by seungchan100** [comment]
"게임명 : 없음" 도 입력하지 못하게 할지 결정필요?
--> 못하게 하는게 맞을거 같긴합니다

**Comment by yjhwang93** [comment]
무조건 게임명을 선택하도록, 게임명 없음 콘텐츠도 등록이 되지 않도록

**Comment by seungchan100** [comment]
11/21 00:32 적용되었습니다.

**Comment by yjhwang93** [comment]
굿잡.. 확실히 자료가 좀더 정제된 자료가 들어오는듯..
