### ISSUE TITLE
[개선] 좋아요 후 페이지 리플래쉬 필요

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#174]
좋아요 버튼을 누른후에 아무런 반응이 없어서 좋아요를 눌렀는지 확인이 어려움
"이 자료를 좋아하셨습니다." 라는 메시지와 페이지 리플래시 를 통해 좋아요 카운트가 올라갈 필요가 있어 보임

https://www.gamess.co.kr/board_board_view.php?no=20671&code=1969&type=pds_game

질문
- 좋아요를 선택하면 좋아요를 선택한 게임에 대한 기록이 남는지? 아니면 단순히 좋아요 카운트만 올라가는 건지?
- 유저의 좋아요 정보를 바탕으로 게임을 추천해주려고함.

**Comment by seungchan100** [comment]
수정완료.


좋아요를 선택하면 좋아요를 선택한 게임에 대한 기록이 남는지? 아니면 단순히 좋아요 카운트만 올라가는 건지?
--> pds_like 테이블에 기록이 남습니다.
