### ISSUE TITLE
gswebmicro에  bookstackapp.com 설치 하기

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#191]
micro g1 서버 구매 완료

상세 로그인 정보는 아래 문서 참고
https://docs.google.com/spreadsheets/d/16HRn5gjIBHd5Li0AA1O8_7zKMT7DdZISmva_zpPGTT8/edit?gid=0#gid=0

이후 프로세스

https://www.bookstackapp.com/ 설치
도메인 : https://book.gamess.co.kr/
게임세상 계정과 해당 계정 서비스 SSO
IGN 에 있는 게임매뉴얼 1개 택해서 번역 후 모두 업로드 (발더스게이트3 1순위) https://www.ign.com/wikis/baldurs-gate-3
한국 스팀에서 가장많이 검색된게임

발더스게이트3
이터널리턴
배틀그라운드
아머드코어6:루비콘의 화염
호그와트레거시
노맨즈스카이
로스트아크
발로란트
서든어택
에이펙스 레전드
도타2
GTA V
철권8
헬다이버즈2
리썰 컴퍼니
그랑블루 판타지
풋볼매니저 2024
스타듀 밸리
레드 데드 리뎀션2

wiki 와 유사한 플랫폼
https://www.bookstackapp.com/

현재 국내에서 제공되고 있는 서비스
https://wikidocs.net/

각 게임별 공략자료집을 위의 bookstackapp 을 설치후 고도화 하면 좋을것으로 보임

공략집 플랫폼 만들기 > 유저들이 공략집 업데이트 > 이 자료 기반으로 AI 매뉴얼 제작 > AI 공략집에서 만들어진 좋은자료는 다시 wiki 로 업데이트, 선순환 구조 만들기

**Comment by seungchan100** [comment]
https://book.gamess.co.kr
admin@admin.com / password

**Comment by seungchan100** [comment]
gswebmicro 없애도 됨
(docker 사용해서  기존 서버에 설치함)

**Comment by yjhwang93** [comment]
내일 접속해볼께..

**Comment by yjhwang93** [comment]
https://book.gamess.co.kr/books

작성중, 우선 발더스 게이트3 콘텐츠 모두 업데이트하고 이후 레이아웃은 이후 수정예정

**Comment by yjhwang93** [comment]
gswebmicro 반납 완료
