### ISSUE TITLE
https://m.searchad.naver.com/ 검토

### ISSUE THREAD

**Issue by seungchan100** [2pewscom/gs1.1#196]

**Comment by yjhwang93** [comment]
https://searchad.naver.com/my-screen
이건 네이버에 광고를 올리는 광고 플랫폼

https://bizschool.naver.com/online/course/64919/lecture/1461066
돈을 벌기 위해서는 네이버애드포스트라는 상품 존재, 네이버 블로그 등 네이버 플랫폼 에서만 수익창출 가능
