### ISSUE TITLE
[운영] book.gamess.co.kr 사이트맵 만들기

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#203]

**Comment by yjhwang93** [comment]
[sitemap.txt](https://github.com/user-attachments/files/17950340/sitemap.txt)


사이트맵

**Comment by seungchan100** [comment]
옮기도록 필요

**Comment by seungchan100** [comment]
/home/gamess/public_html/book.gamess.co.kr
 경로에서 아래 명령어 실행
docker cp sitemap.txt bookstack:/app/www/public/

https://book.gamess.co.kr/sitemap.txt 에서 확인가능

속성추가하셨을까요? : https://search.google.com/u/3/search-console/welcome?hl=ko

**Comment by yjhwang93** [comment]
반영된것 확인.. search.google.com 에 반영함
