### ISSUE TITLE
[개선] 글작성시 동영상 추가 불가

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#213]
https://www.gamess.co.kr/upload_main?code=1596

글 작성시 유튜브 동영상등 영상 추가 불가

**Comment by seungchan100** [comment]
https://www.gamess.co.kr/upload_main2?type=pds_manual&code=

ckeditor 버전업글함 43.0.0 -> 44.0.0

**Comment by seungchan100** [comment]
반영 필요. 
목록기능 추가 필요.
