### ISSUE TITLE
[개선] 모바일 화면에서 일부 불편한 UI 개선

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#222]
PC 에서 줄인 화면은 정상적으로 보이나 핸드폰에서는 레이아웃이 일부 깨짐

https://www.gamess.co.kr/board_board_view?code=2501&no=14289&type=pds_game

![Image](https://github.com/user-attachments/assets/437fe9d6-d1f3-40c7-bc8f-40e78fc90851)

![Image](https://github.com/user-attachments/assets/14260e76-f39a-4a78-a914-50f9b5d83ae5)

**Comment by seungchan100** [comment]
아래와 같이 개선
1. 목록위치 바꿈
2. 신고는 내가 작성한 글이 아닐때만 보임
3. 수정, 삭제는 내가 작성한 글일때만 보임
4. 다음/이전자료는 문구수정 및 자료없을시 disabled처리
5. 다음, 이전, 목록 버튼 ui 수정

https://www.gamess.co.kr/board_board_view2?no=49217&code=428&type=board_free

![Image](https://github.com/user-attachments/assets/898e2318-d721-4587-8a35-c5cc9ae82664)

**Comment by yjhwang93** [comment]
확인 완료.. 라이브 반영 고고싱!

**Comment by seungchan100** [comment]
12/18 라이브반영했습니다

**Comment by yjhwang93** [comment]
관리자로 로그인시 수정삭제 버튼이 보지 않음 관리자쪽을 모두 관리자로 이관하는 거라면
관리자로 수정삭제 기능을 넘겨도 될것 같음
다만, 삭제시, GM 이 차감되는 기능은 관리자에 추가되어야함

**Comment by seungchan100** [comment]
관리자로 로그인시 수정삭제 버튼이 보이도록 설정했습니다
