### ISSUE TITLE
[개선] 게임세상 > 상세보기 페이지 > 마우스 오른쪽 버튼 클릭 불가

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#225]
게임세상 상세 페이지에서 마우스 오른쪽 클릭불가 기능 제공으로 콘텐츠 보호

https://www.gamess.co.kr/board_board_view.php?no=52152&code=5803&type=board_free

------------------
```
<script>
  document.addEventListener("contextmenu", function (event) {
    event.preventDefault();
    alert("오른쪽 클릭이 비활성화되었습니다.");
  });
</script>
```

**Comment by seungchan100** [comment]
/components/_script.php 에 추가
