### ISSUE TITLE
2.8 마이 > 관심 게임 관리,,2.9 마이 > 관심 친구 관리 개발

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#227]

**Comment by seungchan100** [comment]
사용률 저조한데, 유지보수 비용 감소를 위해 기능제거하는것 검토하고자 합니다.
2012년 이후  84건등록
![Image](https://github.com/user-attachments/assets/a0918f42-7c8a-4a77-9752-f26b9b1e472f)

**Comment by seungchan100** [comment]
MariaDB [gamess_renewal]> select * from my_friends;
+---------+------------+---------------------+
| mb_num  | friend_num | time                |
+---------+------------+---------------------+
| 1961988 |    1979427 | 2012-02-26 14:22:43 |
| 1961988 |      91336 | 2012-02-26 14:23:48 |
| 1979427 |    1979427 | 2012-02-28 22:12:03 |
| 1961988 |      19057 | 2012-03-01 17:00:37 |
| 1961988 |       3882 | 2012-03-01 17:00:57 |
| 1979427 |    1961988 | 2012-03-15 15:32:02 |
|   91336 |      91336 | 2012-03-16 09:17:40 |
|   91336 |    1961988 | 2012-03-16 09:17:49 |
| 1991484 |    1991484 | 2012-06-07 08:07:38 |
|   91336 |     276323 | 2012-11-15 11:44:05 |
| 2001462 |    2001462 | 2013-02-02 20:25:04 |
|      16 |         16 | 2013-03-21 12:35:33 |
| 2006530 |    2006266 | 2013-08-08 22:03:40 |
| 2006530 |    2006530 | 2013-08-08 22:12:55 |
| 2006530 |    1961988 | 2013-08-09 00:53:42 |
| 2009179 |     360616 | 2013-10-08 04:25:48 |
| 1989302 |    1989302 | 2013-12-27 12:22:26 |
| 2015386 |     508698 | 2014-01-22 18:51:48 |
| 2015857 |     232133 | 2014-01-29 02:40:20 |
|   91336 |    2018685 | 2014-04-10 17:26:03 |
| 2020933 |    2020933 | 2014-05-08 21:21:19 |
| 1497648 |      91336 | 2014-07-21 11:11:03 |
| 2023713 |    2023713 | 2014-08-03 21:35:38 |
| 2024421 |    2024421 | 2014-08-19 11:41:56 |
| 1805008 |    1805008 | 2014-11-28 15:23:39 |
| 2035091 |    2035091 | 2015-05-03 19:34:54 |
| 2035315 |    2035315 | 2015-05-08 22:08:46 |
| 1111929 |      58470 | 2015-09-09 21:10:22 |
| 1251664 |    1251664 | 2015-11-05 01:58:24 |
| 2044326 |    2044326 | 2016-01-08 12:28:31 |
| 2045591 |    2045591 | 2016-02-14 20:55:58 |
| 2049398 |      58470 | 2016-07-22 03:37:53 |
| 2049507 |      63152 | 2016-07-30 01:22:28 |
| 1961988 |    1961988 | 2016-09-11 23:27:03 |
| 2050492 |    2050492 | 2016-09-27 19:37:47 |
| 1968333 |    1968333 | 2017-06-01 01:29:43 |
|   60823 |      60823 | 2018-01-03 22:43:45 |
| 2053656 |    2053656 | 2018-02-24 14:01:02 |
| 2060598 |      63152 | 2021-11-15 20:51:26 |
| 1994372 |     610381 | 2022-04-29 05:49:54 |
| 1961988 |    1979427 | 2012-02-26 14:22:43 |
| 1961988 |      91336 | 2012-02-26 14:23:48 |
| 1979427 |    1979427 | 2012-02-28 22:12:03 |
| 1961988 |      19057 | 2012-03-01 17:00:37 |
| 1961988 |       3882 | 2012-03-01 17:00:57 |
| 1979427 |    1961988 | 2012-03-15 15:32:02 |
|   91336 |      91336 | 2012-03-16 09:17:40 |
|   91336 |    1961988 | 2012-03-16 09:17:49 |
| 1991484 |    1991484 | 2012-06-07 08:07:38 |
|   91336 |     276323 | 2012-11-15 11:44:05 |
| 2001462 |    2001462 | 2013-02-02 20:25:04 |
|      16 |         16 | 2013-03-21 12:35:33 |
| 2006530 |    2006266 | 2013-08-08 22:03:40 |
| 2006530 |    2006530 | 2013-08-08 22:12:55 |
| 2006530 |    1961988 | 2013-08-09 00:53:42 |
| 2009179 |     360616 | 2013-10-08 04:25:48 |
| 1989302 |    1989302 | 2013-12-27 12:22:26 |
| 2015386 |     508698 | 2014-01-22 18:51:48 |
| 2015857 |     232133 | 2014-01-29 02:40:20 |
|   91336 |    2018685 | 2014-04-10 17:26:03 |
| 2020933 |    2020933 | 2014-05-08 21:21:19 |
| 1497648 |      91336 | 2014-07-21 11:11:03 |
| 2023713 |    2023713 | 2014-08-03 21:35:38 |
| 2024421 |    2024421 | 2014-08-19 11:41:56 |
| 1805008 |    1805008 | 2014-11-28 15:23:39 |
| 2035091 |    2035091 | 2015-05-03 19:34:54 |
| 2035315 |    2035315 | 2015-05-08 22:08:46 |
| 1111929 |      58470 | 2015-09-09 21:10:22 |
| 1251664 |    1251664 | 2015-11-05 01:58:24 |
| 2044326 |    2044326 | 2016-01-08 12:28:31 |
| 2045591 |    2045591 | 2016-02-14 20:55:58 |
| 2049398 |      58470 | 2016-07-22 03:37:53 |
| 2049507 |      63152 | 2016-07-30 01:22:28 |
| 1961988 |    1961988 | 2016-09-11 23:27:03 |
| 2050492 |    2050492 | 2016-09-27 19:37:47 |
| 1968333 |    1968333 | 2017-06-01 01:29:43 |
|   60823 |      60823 | 2018-01-03 22:43:45 |
| 2053656 |    2053656 | 2018-02-24 14:01:02 |
| 2070477 |    2070477 | 2023-11-24 22:49:03 |
|    NULL |    2070457 | 2024-02-10 18:10:08 |
| 2072699 |    2072699 | 2024-06-19 17:36:02 |
| 2072897 |      88157 | 2024-07-16 22:09:10 |
| 2073349 |    2072860 | 2024-08-23 00:22:50 |
| 2074662 |    2074662 | 2024-11-10 00:52:50 |
+---------+------------+---------------------+
84 rows in set (0.00 sec)

MariaDB [gamess_renewal]> select * from my_friends;
+---------+------------+---------------------+
| mb_num  | friend_num | time                |
+---------+------------+---------------------+
| 1961988 |    1979427 | 2012-02-26 14:22:43 |
| 1961988 |      91336 | 2012-02-26 14:23:48 |
| 1979427 |    1979427 | 2012-02-28 22:12:03 |
| 1961988 |      19057 | 2012-03-01 17:00:37 |
| 1961988 |       3882 | 2012-03-01 17:00:57 |
| 1979427 |    1961988 | 2012-03-15 15:32:02 |
|   91336 |      91336 | 2012-03-16 09:17:40 |
|   91336 |    1961988 | 2012-03-16 09:17:49 |
| 1991484 |    1991484 | 2012-06-07 08:07:38 |
|   91336 |     276323 | 2012-11-15 11:44:05 |
| 2001462 |    2001462 | 2013-02-02 20:25:04 |
|      16 |         16 | 2013-03-21 12:35:33 |
| 2006530 |    2006266 | 2013-08-08 22:03:40 |
| 2006530 |    2006530 | 2013-08-08 22:12:55 |
| 2006530 |    1961988 | 2013-08-09 00:53:42 |
| 2009179 |     360616 | 2013-10-08 04:25:48 |
| 1989302 |    1989302 | 2013-12-27 12:22:26 |
| 2015386 |     508698 | 2014-01-22 18:51:48 |
| 2015857 |     232133 | 2014-01-29 02:40:20 |
|   91336 |    2018685 | 2014-04-10 17:26:03 |
| 2020933 |    2020933 | 2014-05-08 21:21:19 |
| 1497648 |      91336 | 2014-07-21 11:11:03 |
| 2023713 |    2023713 | 2014-08-03 21:35:38 |
| 2024421 |    2024421 | 2014-08-19 11:41:56 |
| 1805008 |    1805008 | 2014-11-28 15:23:39 |
| 2035091 |    2035091 | 2015-05-03 19:34:54 |
| 2035315 |    2035315 | 2015-05-08 22:08:46 |
| 1111929 |      58470 | 2015-09-09 21:10:22 |
| 1251664 |    1251664 | 2015-11-05 01:58:24 |
| 2044326 |    2044326 | 2016-01-08 12:28:31 |
| 2045591 |    2045591 | 2016-02-14 20:55:58 |
| 2049398 |      58470 | 2016-07-22 03:37:53 |
| 2049507 |      63152 | 2016-07-30 01:22:28 |
| 1961988 |    1961988 | 2016-09-11 23:27:03 |
| 2050492 |    2050492 | 2016-09-27 19:37:47 |
| 1968333 |    1968333 | 2017-06-01 01:29:43 |
|   60823 |      60823 | 2018-01-03 22:43:45 |
| 2053656 |    2053656 | 2018-02-24 14:01:02 |
| 2060598 |      63152 | 2021-11-15 20:51:26 |
| 1994372 |     610381 | 2022-04-29 05:49:54 |
| 1961988 |    1979427 | 2012-02-26 14:22:43 |
| 1961988 |      91336 | 2012-02-26 14:23:48 |
| 1979427 |    1979427 | 2012-02-28 22:12:03 |
| 1961988 |      19057 | 2012-03-01 17:00:37 |
| 1961988 |       3882 | 2012-03-01 17:00:57 |
| 1979427 |    1961988 | 2012-03-15 15:32:02 |
|   91336 |      91336 | 2012-03-16 09:17:40 |
|   91336 |    1961988 | 2012-03-16 09:17:49 |
| 1991484 |    1991484 | 2012-06-07 08:07:38 |
|   91336 |     276323 | 2012-11-15 11:44:05 |
| 2001462 |    2001462 | 2013-02-02 20:25:04 |
|      16 |         16 | 2013-03-21 12:35:33 |
| 2006530 |    2006266 | 2013-08-08 22:03:40 |
| 2006530 |    2006530 | 2013-08-08 22:12:55 |
| 2006530 |    1961988 | 2013-08-09 00:53:42 |
| 2009179 |     360616 | 2013-10-08 04:25:48 |
| 1989302 |    1989302 | 2013-12-27 12:22:26 |
| 2015386 |     508698 | 2014-01-22 18:51:48 |
| 2015857 |     232133 | 2014-01-29 02:40:20 |
|   91336 |    2018685 | 2014-04-10 17:26:03 |
| 2020933 |    2020933 | 2014-05-08 21:21:19 |
| 1497648 |      91336 | 2014-07-21 11:11:03 |
| 2023713 |    2023713 | 2014-08-03 21:35:38 |
| 2024421 |    2024421 | 2014-08-19 11:41:56 |
| 1805008 |    1805008 | 2014-11-28 15:23:39 |
| 2035091 |    2035091 | 2015-05-03 19:34:54 |
| 2035315 |    2035315 | 2015-05-08 22:08:46 |
| 1111929 |      58470 | 2015-09-09 21:10:22 |
| 1251664 |    1251664 | 2015-11-05 01:58:24 |
| 2044326 |    2044326 | 2016-01-08 12:28:31 |
| 2045591 |    2045591 | 2016-02-14 20:55:58 |
| 2049398 |      58470 | 2016-07-22 03:37:53 |
| 2049507 |      63152 | 2016-07-30 01:22:28 |
| 1961988 |    1961988 | 2016-09-11 23:27:03 |
| 2050492 |    2050492 | 2016-09-27 19:37:47 |
| 1968333 |    1968333 | 2017-06-01 01:29:43 |
|   60823 |      60823 | 2018-01-03 22:43:45 |
| 2053656 |    2053656 | 2018-02-24 14:01:02 |
| 2070477 |    2070477 | 2023-11-24 22:49:03 |
|    NULL |    2070457 | 2024-02-10 18:10:08 |
| 2072699 |    2072699 | 2024-06-19 17:36:02 |
| 2072897 |      88157 | 2024-07-16 22:09:10 |
| 2073349 |    2072860 | 2024-08-23 00:22:50 |
| 2074662 |    2074662 | 2024-11-10 00:52:50 |
+---------+------------+---------------------+
84 rows in set (0.00 sec)

**Comment by seungchan100** [comment]
메시지 기능도 삭제 검토?


MariaDB [gamess_renewal]> select count(1) from message;
+----------+
| count(1) |
+----------+
|       73 |
+----------+
1 row in set (0.00 sec)

**Comment by seungchan100** [comment]
메시지 / 친구 기능 빼는것으로
