### ISSUE TITLE
전체게시판만들기

### ISSUE THREAD

**Issue by seungchan100** [2pewscom/gs1.1#230]
프리서버는빼고

**Comment by seungchan100** [comment]
https://www.gamess.co.kr/board_board_list?type=all

메인 최신글과 동일함 (프리서버/뉴스 제외 )

**Comment by yjhwang93** [comment]
확인했고 이견 없음 GNB 메뉴에 추가 고고싱!!

**Comment by seungchan100** [comment]
![image](https://github.com/user-attachments/assets/324bee6f-97fa-4daf-a6d4-a942de39d0ae)
12/18 라이브 반영하였습니다
