### ISSUE TITLE
[개선] 1:1 문의 답변 내용 저장 기능

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#235]
현재 1:1 문의의 경우 문의시 문의 내용은 저장됨
문의 답변 내용은 한번 보여지고 끝
문의 답변 내용이 저장되면 좋겠음

https://www.gamess.co.kr/yjhwang/qa_list.php

주요 기능

문의 답변 내용에 대한 저장
문의 내용이 이메일로 문의 유저에게 답변이 됨

**Comment by seungchan100** [comment]
앞으로 답변하는거에 대해서 표시됨

![Image](https://github.com/user-attachments/assets/13ee059b-3041-4c4e-86c7-1e3f40329711)
