### ISSUE TITLE
[버그] 이전 다음페이지 이동시 오류

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#236]
https://www.gamess.co.kr/board_board_view?code=4744&no=20729&type=pds_game

이전 페이지, 다음 페이지 클릭시 이동되는 페이지

해당 게시판에 보이는 리스트에 대해 이전/다음 페이지로 이동이 되어야할것으로 보임

**Comment by seungchan100** [comment]
분류+ 게임 기준으로 이전/다음자료로
