### ISSUE TITLE
[버그] 게임홈 > 홈

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#41]
https://www.gamess.co.kr/gs1.1/gamehome-home.php

완료

**Comment by seungchan100** [comment]
게임명 우측에 영문명추가필요

**Comment by seungchan100** [comment]
게임 이미지 수정하는거는 관리자만 가능하도록

**Comment by seungchan100** [comment]
https://gamess.co.kr/game_main2.php?code=2461 와 같이 기존 game_main에 2를 붙이면됨.

**Comment by seungchan100** [comment]
로그인이 되지 않음--> 수정후 반영필요
