### ISSUE TITLE
[반영필요] 검색결과

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#58]
https://www.gamess.co.kr/gs1.1/search-result.php

검색결과 페이지 완료

**Comment by seungchan100** [comment]
게임명, 제목,   까지만 검색되도록

**Comment by seungchan100** [comment]
https://gamess.co.kr/search_main3.php?keyword=tt#google_vignette

**Comment by seungchan100** [comment]
아래 항목 완료 : https://gamess.co.kr/search_main3.php?keyword=%EC%8A%A4%ED%83%80
검색 결과물에 대한 숫자 추가
검색결과물에서 검색된 키워드에 색깔 추가
