### ISSUE TITLE
[개선] 구 게임홈 > 리스트 > 커뮤니티에서 프리서버 홍보 제외

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#65]
https://www.gamess.co.kr/game_main.php?class=all&code=648&type=home

게임홈 > 메인 : 최신업데이트 자료
게임홈 > 메인 : 인기자료
게임홈 > 커뮤니티

프리서버 홍보 관련 콘텐츠가 노출이 되지 않도록

**Comment by seungchan100** [comment]
신규 페이지 개발예정이므로 drop 하고자 합니다

**Comment by Gamesscokr** [comment]
이견없습니다.
