### ISSUE TITLE
[개발] admin > 게임자료실 관리 내 모든 항목 수정가능기능 개발

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#73]
관리자 > 게임 자료실 관리
https://www.gamess.co.kr/yjhwang/board_list_admin.php?table=pds_game

완료
- 잘못 입력된 게임명을 수정할수 있는 기능이 없어 개발함, 게임 자료실 개발 완료

추가 개발 필요
- 게임뉴스
- 커뮤니티

**Comment by seungchan100** [comment]
내용/좋아요 수정가능하도록 개선

**Comment by seungchan100** [comment]
좋아요 수정가능하도록 개선됨
