### ISSUE TITLE
메뉴정리

### ISSUE THREAD

**Issue by seungchan100** [2pewscom/gs1.1#8]
참고용사이트 
gamevue.co.kr
https://silpir.net/
 https://www.onlifezone.com/

**Comment by JiwonNJihoo** [comment]
게임별홈
게임뉴스
자료실 : 일반자료실 / 게임자료실 / 패치자료실
커뮤니티 : 자유게시판 / 자료요청 / 프리서버 홍보
고객지원

--------------
공략/에디터/치트/세이브/맵/리플레이/게임유틸/멀티미디어/동영상은 일반자료실로 통합
공식패치 / 비공식패치 / 노시디패치 / 한글화 패치 패치자료실로 통합
고전게임 / 에뮬게임 / 게임은 게임자료실로 통합
멀티미디어의 동영상 이미지는 일반자료실로 이동

**Comment by seungchan100** [comment]
좌측메뉴 날리고 gnb만 유지해보기로?
