### ISSUE TITLE
[QA] 탈퇴하기 페이지

### ISSUE THREAD

**Issue by yjhwang93** [2pewscom/gs1.1#92]
https://www.gamess.co.kr/mypage-getleave.php
퍼블리싱 완료

**Comment by seungchan100** [comment]
# 테스트 항목
탈퇴후 메일이 보내졌는가?
탈퇴후 https://gamess.co.kr 로 이동하면 로그인이 풀렸는가?
탈퇴후 로그인이 불가능한가?

**Comment by seungchan100** [comment]
구글 회원에 대한 안내 문구 추가필요(영준형)
